services:
  web:
    build: ./frontend/
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
  backend:
    build: ./backend/
    ports:
      - '81:3000'
    environment:
      - NODE_ENV=production
